version: '3.8'

services:
  postgres-db:
    image: postgres:latest
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: db_name
    healthcheck:
      test: [ 'CMD', 'pg_isready', '-U', 'user' ]
      interval: 10s
      timeout: 5s
      retries: 3
    networks:
      - backend_net

  ai-pedal-backend:
    build: ./ai-pedal-backend
    environment:
      DATABASE_URL: postgres://user:password@postgres-db:5432/db_name
      ENV_VAR_ONE: value_one
      ENV_VAR_TWO: value_two
    healthcheck:
      test: [ 'CMD-SHELL', 'curl -f http://localhost:5000/health || exit 1' ]
      interval: 30s
      timeout: 10s
      retries: 5
    networks:
      - backend_net

networks:
  backend_net:
    driver: bridge
